//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngitelExam.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appuntamento
    {
        public int AppuntamentoId { get; set; }
        public int DayId { get; set; }
        public int FamigliaId { get; set; }
        public string Status { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Famiglia Famiglia { get; set; }
    }
}
