//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngitelExam.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string Nome { get; set; }
        public int FamigliaId { get; set; }
        public Nullable<int> VeicoloId { get; set; }
    
        public virtual Famiglia Famiglia { get; set; }
        public virtual Veicolo Veicolo { get; set; }
    }
}
